language: ruby
rvm:
  - "2.1.1"
env:
  - DB=postgresql
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
before_script:
  - psql -c 'create database watstickstest;' -U postgres
  - bundle exec rake db:create RAILS_ENV=test
